name: flutter_weather_demo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.6.0 <3.0.0'

publish_to:none

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  rxdart: ^0.24.1
  flutter_command: 
    path: ../
  functional_listener: any

flutter:
  uses-material-design: true
